import { useCallback, useEffect, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import AdminPanel from './AdminPanel';

type User = { user_id: string; role: string; employee_id: string | null };
type Skill = {skill_id:string;name:string;current:number;required:number|null;critical:boolean;gap:number};
type Profile = {employee:{employee_id:string;full_name:string;role:string;grade:string;department:string;preferred_language:string};target:{role:string;grade:string};readiness:{pct:number;critical_met:number;critical_total:number};skills:Skill[];history:{record_id:string;title:string;date:string;status:string}[];state_revision:number};
type Event = {event_id:string;title:string;type:string;format:string;duration_hours:number;next_session:string|null;reasons:string[];closes:{name:string;from:number;to:number}[]};
type Recommendations = {state_revision:number;source:string;fallback_reason:string|null;recommendations:Event[];empty_reason:string|null;not_chosen:{text:string}|null;uncovered_critical:string[]};
const statuses:Record<string,string> = {completed:'Завершено',in_progress:'В процессе',overdue:'Просрочено',registered:'Запланировано',no_show:'Не посещено',declined:'Отклонено',dropped:'Прервано'};
const emptyReasons:Record<string,string> = {target_covered:'Требования цели уже закрыты. Обсуди следующий шаг с руководителем.',no_eligible_events:'Сейчас нет подходящих активностей.',missing_prerequisites:'Сначала нужно освоить базовые навыки.',catalog_gap:'В каталоге пока нет активности для этого разрыва.'};
const labels = {ru:{plan:'Мой план развития',profile:'Мой профиль',history:'История активности',team:'Команда и аналитика',skills:'Карта навыков',recommend:'Рекомендовано для тебя',complete:'Отметить выполнение',refresh:'Обновить',logout:'Выйти'},kk:{plan:'Менің даму жоспарым',profile:'Менің профилім',history:'Белсенділік тарихы',team:'Команда және талдау',skills:'Дағдылар картасы',recommend:'Сізге ұсынылады',complete:'Аяқталды деп белгілеу',refresh:'Жаңарту',logout:'Шығу'},en:{plan:'My growth plan',profile:'My profile',history:'Activity history',team:'Team analytics',skills:'Skills map',recommend:'Recommended for you',complete:'Mark complete',refresh:'Refresh',logout:'Sign out'}};

export default function App() {
  const [user,setUser]=useState<User|null>(null), [token,setToken]=useState('');
  const [username,setUsername]=useState('employee'),[password,setPassword]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[recs,setRecs]=useState<Recommendations|null>(null);
  const [selected,setSelected]=useState(''),[tab,setTab]=useState('plan'),[lang,setLang]=useState<'ru'|'kk'|'en'>('ru');
  const [refreshVersion,setRefreshVersion]=useState(0);
  const [error,setError]=useState(''),[recError,setRecError]=useState(''),[notice,setNotice]=useState('');
  const [loading,setLoading]=useState(false),[recLoading,setRecLoading]=useState(false),[completing,setCompleting]=useState('');
  const [confirm,setConfirm]=useState<Event|null>(null);
  const generation=useRef(0), revision=useRef(0); const t=labels[lang];
  const logout=useCallback(()=>{generation.current++;setToken('');setUser(null);setProfile(null);setRecs(null);setSelected('');setPassword('');setError('');setRecError('');setNotice('');setConfirm(null);setCompleting('');setLoading(false);setRecLoading(false)},[]);
  const request=useCallback(async <T=any,>(path:string,options:RequestInit={}):Promise<T>=>{
    const headers=new Headers(options.headers); if(token)headers.set('Authorization',`Bearer ${token}`);
    if(options.body && !(options.body instanceof FormData))headers.set('Content-Type','application/json');
    const response=await fetch(path,{...options,headers,signal:options.signal??AbortSignal.timeout(20000)});
    const body=await response.json();
    if(!response.ok){if(response.status===401 && token)logout(); const details=body.error?.details?.map((d:any)=>[d.file,d.row,d.field,d.message].filter(Boolean).join(': ')).join('; ');throw new Error((body.error?.message||'Не удалось выполнить запрос')+(details?' — '+details:''));}
    return body as T;
  },[token,logout]);
  async function login(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{
    const result=await request<{access_token:string;user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});
    const response=await fetch('/api/auth/me',{headers:{Authorization:`Bearer ${result.access_token}`}});
    if(!response.ok)throw new Error('Не удалось проверить аккаунт');
    const me:User=await response.json();setToken(result.access_token);setUser(me);setSelected(me.employee_id||'');setTab(me.role==='employee'?'plan':'team');setPassword('');
  }catch(e){setError(e instanceof Error?e.message:'Ошибка входа')}finally{setLoading(false)}}
  const loadRecommendations=useCallback(async(id:string,version:number,gen:number)=>{
    setRecLoading(true);setRecError('');setRecs(null);
    try{const result=await request<Recommendations>(`/api/employees/${encodeURIComponent(id)}/recommendations?lang=${lang}`);
      if(gen===generation.current&&result.state_revision>=version&&result.state_revision>=revision.current)setRecs(result);
    }catch(e){if(gen===generation.current)setRecError(e instanceof Error?e.message:'Не удалось загрузить рекомендации')}
    finally{if(gen===generation.current)setRecLoading(false)}
  },[request,lang]);
  useEffect(()=>{if(!user||!selected)return;const gen=++generation.current;setLoading(true);setError('');setProfile(null);setRecs(null);setConfirm(null);
    request<Profile>(`/api/employees/${encodeURIComponent(selected)}`).then(p=>{if(gen!==generation.current)return;revision.current=p.state_revision;setProfile(p);setLoading(false);void loadRecommendations(selected,p.state_revision,gen)}).catch(e=>{if(gen===generation.current){setError(e.message);setLoading(false)}});
    return()=>{generation.current++};
  },[selected,user,request,loadRecommendations,refreshVersion]);
  async function complete(event:Event){if(!profile||completing)return;const id=profile.employee.employee_id;setCompleting(event.event_id);setConfirm(null);setError('');const gen=++generation.current;setRecs(null);
    try{const result=await request<{status:string;profile:Profile}>(`/api/employees/${encodeURIComponent(id)}/activities/${encodeURIComponent(event.event_id)}/complete`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({occurrence_key:event.event_id==='EV_036'?event.next_session:null})});
      if(gen!==generation.current)return;setProfile(result.profile);revision.current=result.profile.state_revision;setNotice(result.status==='already_completed'?'Это выполнение уже учтено.':'Готово! Навыки и прогресс обновлены. Подбираем следующий шаг.');void loadRecommendations(id,result.profile.state_revision,gen);
    }catch(e){if(gen===generation.current){setError(e instanceof Error?e.message:'Ошибка выполнения');void loadRecommendations(id,revision.current,gen)}}finally{setCompleting('')}}
  if(!user)return <div className="login-page"><section className="login-art"><div className="brand"><span className="brand-mark">↗</span> Career Quest</div><span className="eyebrow">ТВОЯ КАРЬЕРА. ТВОЙ МАРШРУТ.</span><h1>Большие цели.<br/>Понятные шаги.</h1><p>Превращай обучение в реальные навыки.<br/>Построй свой путь к следующему грейду.</p><div className="login-orbit"><span>LEARN</span><strong>↗</strong><span>GROW</span></div><small>HACKALEM · КОМАНДНЫЙ ПРОТОТИП</small></section><section className="login-card"><span className="badge">Career development platform</span><h2>Твой следующий шаг начинается здесь</h2><p className="muted">Войди, чтобы увидеть свой персональный план развития.</p><form onSubmit={login}><label className="field">Логин<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label className="field">Пароль<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div role="alert" className="alert error">{error}</div>}<button className="button primary" disabled={loading}>{loading?'Входим…':'Войти в Career Quest'} <span>↗</span></button></form><p className="muted">Демо-аккаунты: employee · hr · admin<br/>Пароль — DEMO_PASSWORD из локального .env.</p></section></div>;
  const p=profile;const initials=p?.employee.full_name.split(' ').map(n=>n[0]).slice(0,2).join('')||user.role.slice(0,2).toUpperCase();
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">↗</span> Career Quest</div><span className="eyebrow">ПРОСТРАНСТВО РОСТА</span><nav>{(user.role==='employee'||selected)&&[['plan','◈',t.plan],['profile','◎',t.profile],['history','◷',t.history]].map(([id,icon,label])=><button key={id} className={`nav-button ${tab===id?'active':''}`} onClick={()=>setTab(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}{user.role!=='employee'&&<button className={`nav-button ${tab==='team'?'active':''}`} onClick={()=>setTab('team')}><span aria-hidden="true">▦</span>{t.team}</button>}</nav><div className="sidebar-bottom"><div className="sidebar-tip">Каждый новый навык —<br/><strong>шаг к большему.</strong><span>↗</span></div><button className="nav-button" onClick={logout}>{t.logout}</button><small>Career Quest · HackAlem 2026</small></div></aside><main className="main"><header className="topbar"><span className="muted">Твой маршрут развития <span aria-hidden="true"> / </span> <strong>{tab==='team'?t.team:tab==='history'?t.history:tab==='profile'?t.profile:t.plan}</strong></span><div className="toolbar"><select aria-label="Язык интерфейса" value={lang} onChange={e=>setLang(e.target.value as typeof lang)}><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select><span className="avatar">{initials}</span></div></header>
  {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}<button className="button ghost" onClick={()=>setNotice('')}>×</button></div>}
  {tab==='team'?<><span className="eyebrow">РАЗВИТИЕ КОМАНДЫ</span><h1 className="page-title">Видеть потенциал. Помогать расти.</h1><p className="page-subtitle">Навыки, участие и следующие шаги — в одном месте.</p><AdminPanel request={request} user={user} onSelectEmployee={id=>{setSelected(id);setRefreshVersion(v=>v+1);setTab('plan')}}/></>:loading?<div className="panel skeleton" role="status">Загружаем твой маршрут…</div>:p?<>
  <div className="profile-header"><div><span className="eyebrow">ТВОЙ ПЕРСОНАЛЬНЫЙ МАРШРУТ</span><h1 className="page-title">{tab==='history'?'Твой путь в действиях':`Привет, ${p.employee.full_name.split(' ')[0]}!`}</h1><p className="page-subtitle">{p.employee.role} · {p.employee.grade} <span className="muted">/ {p.employee.department}</span></p></div><span className="badge">{p.employee.employee_id}</span></div>
  {tab!=='history'&&<><section className="hero"><div className="hero-copy"><span className="eyebrow">СЛЕДУЮЩАЯ ОСТАНОВКА</span><h2>{p.target.grade}<br/><span>{p.target.role}</span></h2><p>Твой рост начинается с одного действия.<br/>Мы подобрали шаги под твои навыки и цель.</p><span className="badge">{p.readiness.critical_met} из {p.readiness.critical_total} критичных навыков закрыто</span></div><div className="hero-stats"><div className="readiness-ring" style={{'--progress':`${p.readiness.pct}%`} as CSSProperties}><div><strong>{p.readiness.pct}<small>%</small></strong><span>покрытие требований</span></div></div><small>Не вероятность повышения</small></div></section><div className="stats-grid"><div className="stat-card"><span>Навыки в профиле</span><strong>{p.skills.length}<small> направлений</small></strong></div><div className="stat-card"><span>Навыки для развития</span><strong>{p.skills.filter(s=>s.gap>0).length}<small> точек роста</small></strong></div><div className="stat-card"><span>Завершено активностей</span><strong>{p.history.filter(h=>h.status==='completed').length}<small> в истории</small></strong></div></div></>}
  {tab==='history'?<section className="panel"><div className="section-heading"><h2>{t.history}</h2><span className="badge">{p.history.length} записей</span></div><div className="history-list">{p.history.length?p.history.map(h=><div className="history-row" key={h.record_id}><span className="avatar">{h.status==='completed'?'✓':'◷'}</span><div><strong>{h.title}</strong><p className="muted">{h.date}</p></div><span className="chip">{statuses[h.status]||h.status}</span></div>):<p className="empty">Здесь появятся твои активности.</p>}</div></section>:<><div className="content-grid"><section className="panel"><div className="section-heading"><h2>{t.skills}</h2><span className="muted">Уровень / цель</span></div><div className="skills-list">{[...p.skills].sort((a,b)=>Number(b.critical)-Number(a.critical)||b.gap-a.gap).map(s=><div className="skill-row" key={s.skill_id}><div className="skill-topline"><span>{s.name} {s.critical&&<small className="critical">●</small>}</span><strong>{s.current} <span className="muted">/ {s.required??'—'}</span></strong></div><div className="skill-track"><div className="skill-fill" style={{width:`${s.current/5*100}%`}}/>{s.required!==null&&<span className="skill-target" style={{left:`${s.required/5*100}%`}}/>}</div></div>)}</div><p className="muted"><span className="critical">●</span> Критичный навык для целевого грейда · шкала 0–5</p></section><section className="panel growth-note"><span className="eyebrow">ТВОЙ ФОКУС</span><h2>Маленькие шаги.<br/>Заметный результат.</h2><p>Выбирай подходящую активность. После выполнения навыки и готовность обновятся, а план подскажет следующий шаг.</p><div className="growth-art" aria-hidden="true"><span/><span/><span/><span/><strong>↗</strong></div><p className="muted">Данные профиля и прогресс рассчитываются на сервере.</p></section></div>
  <section style={{marginTop:32}}><div className="section-heading"><div><span className="eyebrow">ОТ ЗНАНИЙ К ДЕЙСТВИЮ</span><h2>{t.recommend}</h2></div><button className="button secondary" disabled={recLoading||!!completing} onClick={()=>void loadRecommendations(selected,revision.current,++generation.current)}>{recLoading?'Подбираем…':t.refresh}</button></div>{recLoading?<div className="panel skeleton" role="status">Подбираем активности и объяснения для твоей цели…</div>:recError?<div className="alert error" role="alert">{recError}. Нажми «{t.refresh}», чтобы повторить.</div>:recs?<><p className="muted">{recs.source==='llm'?'✦ Подобрано с AI · на основе твоего профиля':`Расчёт движка без AI · ${recs.fallback_reason||'базовый подбор'}`} {lang!=='ru'&&'· Названия и часть пояснений доступны на языке исходных данных.'}</p><div className="recommendation-grid">{recs.recommendations.map((e,i)=><article className="event-card" key={e.event_id}><div className="event-meta"><span className="chip">{e.type}</span><span>0{i+1} ↗</span></div><h3>{e.title}</h3><p className="muted">{e.format} · {e.duration_hours} ч.{e.next_session&&` · ${e.next_session}`}</p><div className="chips">{e.closes.map(c=><span className="chip" key={c.name}>{c.name}: {c.from} → {c.to}</span>)}</div><small className="muted">Закрытие разрыва до цели</small><ul className="reasons">{e.reasons.map((r,j)=><li key={j}>{r}</li>)}</ul>{user.role!=='hr'&&<button className="button primary" disabled={!!completing} onClick={()=>setConfirm(e)}>{completing===e.event_id?'Сохраняем…':t.complete}<span>✓</span></button>}</article>)}</div>{!recs.recommendations.length&&<div className="panel empty">{emptyReasons[recs.empty_reason||'']||'Нет доступных рекомендаций.'}</div>}{recs.not_chosen&&<p className="muted">{recs.not_chosen.text}</p>}{recs.uncovered_critical.length>0&&<p className="muted">Каталог пока не закрывает критичные навыки: {recs.uncovered_critical.map(id=>p.skills.find(s=>s.skill_id===id)?.name||id).join(', ')}</p>}</>:null}</section></>}
  </>:<div className="panel empty">Выбери сотрудника в разделе команды.</div>}<footer className="muted" style={{marginTop:36,paddingBottom:20}}>Career Quest · Пространство профессионального роста · Демо</footer></main>{confirm&&<div className="modal-backdrop"><section className="panel modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">Активность выполнена?</h2><p>{confirm.title}</p><p className="muted">Подтверди прохождение. Оно сохранится в истории и обновит твой прогресс.</p><div className="toolbar"><button className="button secondary" onClick={()=>setConfirm(null)}>Отмена</button><button className="button primary" onClick={()=>void complete(confirm)}>Да, выполнено</button></div></section></div>}</div>;
}
