import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, Employee, HrOverview, Profile, Recommendations, User } from "./api";
import "./styles.css";

const demoAccounts = { employee: "employee", hr: "hr", admin: "admin" };

function App() {
  const [token, setToken] = useState("");
  const [user, setUser] = useState<User | null>(null);
  const [login, setLogin] = useState({ username: "employee", password: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function signIn(event: React.FormEvent) {
    event.preventDefault(); setError(""); setLoading(true);
    try { const result = await api.login(login.username, login.password); setToken(result.access_token); setUser(result.user); }
    catch (e) { setError((e as Error).message); }
    finally { setLoading(false); }
  }

  if (!user) return <Login login={login} setLogin={setLogin} signIn={signIn} error={error} loading={loading} />;
  return <Shell user={user} onLogout={() => { setToken(""); setUser(null); }}><Dashboard token={token} user={user} /></Shell>;
}

function Login({ login, setLogin, signIn, error, loading }: { login: { username: string; password: string }; setLogin: React.Dispatch<React.SetStateAction<{ username: string; password: string }>>; signIn: (event: React.FormEvent) => void; error: string; loading: boolean }) {
  return <main className="auth-layout"><section className="auth-card"><div className="eyebrow">CAREER QUEST / DEMO</div><h1>Развитие сотрудников<br /><span>по данным, а не наугад.</span></h1><p className="muted">Войдите, чтобы увидеть профиль, AI-рекомендации и HR-аналитику.</p><form onSubmit={signIn}><label>Логин<input value={login.username} onChange={e => setLogin({ ...login, username: e.target.value })} autoFocus /></label><label>Пароль<input type="password" value={login.password} onChange={e => setLogin({ ...login, password: e.target.value })} /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading ? "Входим…" : "Войти в систему"}</button></form><div className="demo-hint">Демо-аккаунты: employee / hr / admin<br />Пароль задаётся в окружении backend.</div></section><div className="auth-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="art-copy"><strong>AI CAREER<br />NAVIGATOR</strong><span>От текущего уровня<br />к следующему шагу.</span></div></div></main>;
}

function Shell({ user, onLogout, children }: { user: User; onLogout: () => void; children: React.ReactNode }) {
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span> career quest</div><div className="top-actions"><span className="role-pill">{user.role}</span><span className="user-id">{user.employee_id || user.user_id}</span><button className="ghost" onClick={onLogout}>Выйти</button></div></header><div className="page-wrap">{children}</div></div>;
}

function Dashboard({ token, user }: { token: string; user: User }) {
  const [tab, setTab] = useState(user.role === "employee" ? "profile" : user.role === "hr" ? "hr" : "jury");
  return <><nav className="tabs">{user.role === "employee" && <button className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}>Мой путь</button>}{user.role !== "employee" && <button className={tab === "hr" ? "active" : ""} onClick={() => setTab("hr")}>HR-обзор</button>}{user.role === "admin" && <button className={tab === "jury" ? "active" : ""} onClick={() => setTab("jury")}>Режим жюри</button>}</nav>{tab === "profile" && <EmployeeView token={token} employeeId={user.employee_id || ""} />}{tab === "hr" && <HrView token={token} />}{tab === "jury" && <JuryView token={token} />}</>;
}

function EmployeeView({ token, employeeId, jury = false }: { token: string; employeeId: string; jury?: boolean }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [recs, setRecs] = useState<Recommendations | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setError(""); setBusy(true); try { const [p, r] = await Promise.all([api.profile(token, employeeId), api.recommendations(token, employeeId)]); setProfile(p); setRecs(r); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { if (employeeId) void load(); }, [employeeId]);
  async function complete(eventId: string, occurrenceKey: string | null) { setBusy(true); try { await api.complete(token, employeeId, eventId, occurrenceKey); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (error) return <Panel><div className="error">{error}</div><button className="secondary" onClick={load}>Повторить</button></Panel>;
  if (!profile || !recs) return <Panel><div className="loading">Загружаем профиль и рекомендации<span>●●●</span></div></Panel>;
  return <section><div className="hero-row"><div><div className="eyebrow">{jury ? "LIVE DEMO / EMPLOYEE PROFILE" : "MY DEVELOPMENT PATH"}</div><h2>{profile.employee.full_name}</h2><p className="muted">{profile.employee.role} · {profile.employee.grade} · {profile.employee.department}</p></div><div className="readiness"><strong>{profile.readiness.pct}%</strong><span>готовность к цели</span><div className="progress"><i style={{ width: `${profile.readiness.pct}%` }} /></div></div></div><div className="grid two"><Panel title="Профиль и цель"><div className="profile-line"><span>Цель</span><strong>{profile.target?.role || "Следующий шаг"} · {profile.target?.grade || "—"}</strong></div><div className="profile-line"><span>Критические навыки</span><strong>{profile.readiness.critical_met} / {profile.readiness.critical_total}</strong></div></Panel><Panel title="Навыки"><div className="skill-list">{profile.skills.slice(0, 5).map(skill => <div className="skill" key={skill.skill_id}><div><strong>{skill.name}</strong>{skill.critical && <span className="tag">critical</span>}</div><span>{skill.current} / {skill.required ?? "—"}</span><div className="mini-progress"><i style={{ width: `${skill.required ? Math.min(100, skill.current / skill.required * 100) : 100}%` }} /></div></div>)}</div></Panel></div><div className="section-heading"><div><div className="eyebrow">AI RECOMMENDATIONS</div><h3>Следующие лучшие шаги</h3></div><span className={`source ${recs.source}`}>{recs.source === "llm" ? "● AI online" : "● fallback"}</span></div>{recs.fallback_reason && <div className="notice">AI временно недоступен — показываем проверенный детерминированный результат.</div>}<div className="rec-grid">{recs.recommendations.map(rec => <article className="rec-card" key={rec.event_id}><div className="rec-top"><span className="rec-type">{rec.type || "activity"} · {rec.format || "online"}</span><span className="impact">+{Math.round((rec.impact || 0) * 100)} impact</span></div><h3>{rec.title}</h3><p className="muted">{rec.duration_hours ? `${rec.duration_hours} ч · ` : ""}{rec.next_session || "Доступно сейчас"}</p><div className="reasons">{(rec.reasons || []).slice(0, 3).map(reason => <div key={reason}>↗ {reason}</div>)}</div>{!jury && <button className="secondary full" disabled={busy} onClick={() => complete(rec.event_id, rec.next_session || null)}>Отметить выполненным</button>}</article>)}</div>{recs.recommendations.length === 0 && <Panel><p className="muted">Подходящих активностей пока нет.</p></Panel>}</section>;
}

function HrView({ token }: { token: string }) { const [data, setData] = useState<HrOverview | null>(null); const [error, setError] = useState(""); useEffect(() => { api.hrOverview(token).then(setData).catch(e => setError((e as Error).message)); }, [token]); if (error) return <Panel><div className="error">{error}</div></Panel>; if (!data) return <Panel><div className="loading">Собираем HR-обзор<span>●●●</span></div></Panel>; return <section><div className="hero-row"><div><div className="eyebrow">TEAM INTELLIGENCE</div><h2>Обзор развития команды</h2><p className="muted">Срез данных, revision {data.state_revision}</p></div><div className="stat-card"><strong>{data.weak_skills.length}</strong><span>зон развития</span></div></div><div className="grid three"><Panel title="Слабые навыки"><div className="metric-list">{data.weak_skills.slice(0, 6).map(item => <div key={item.skill_id}><strong>{item.name}</strong><span>{item.employees} сотрудников</span></div>)}</div></Panel><Panel title="Нужен маршрут"><div className="metric-list">{data.no_recommendation.slice(0, 6).map(item => <div key={item.employee_id}><strong>{item.employee_id}</strong><span>{item.open_gaps.length} gaps</span></div>)}</div></Panel><Panel title="Активности"><div className="metric-list">{data.participation.slice(0, 6).map((item, i) => <div key={i}><strong>{String(item.title || "Activity")}</strong><span>{item.completed}/{item.total}</span></div>)}</div></Panel></div></section>; }

function JuryView({ token }: { token: string }) { const [employees, setEmployees] = useState<Employee[]>([]); const [selected, setSelected] = useState(""); const [upload, setUpload] = useState({ employees: null as File | null, history: null as File | null }); const [message, setMessage] = useState(""); const [error, setError] = useState(""); useEffect(() => { api.employees(token).then(r => { setEmployees(r.employees); setSelected(r.employees[0]?.employee_id || ""); }).catch(e => setError((e as Error).message)); }, [token]); async function submitUpload(event: React.FormEvent) { event.preventDefault(); if (!upload.employees || !upload.history) return setError("Выберите оба файла: employees JSON и history CSV"); setError(""); setMessage(""); try { const result = await api.upload(token, upload.employees, upload.history); setMessage(`Импортировано профилей: ${result.employees_upserted}; записей history: ${result.history_imported}; дублей пропущено: ${result.history_duplicates_skipped}`); const next = await api.employees(token); setEmployees(next.employees); } catch (e) { setError((e as Error).message); } } return <section><div className="hero-row"><div><div className="eyebrow">JURY MODE / DEMO CONTROL</div><h2>Покажем, как система думает</h2><p className="muted">Выберите профиль или загрузите проверочный датасет.</p></div><div className="jury-badge">LIVE<br />DEMO</div></div><Panel title="1. Выбрать сотрудника"><select value={selected} onChange={e => setSelected(e.target.value)}><option value="">Выберите профиль</option>{employees.map(e => <option key={e.employee_id} value={e.employee_id}>{e.employee_id} · {e.full_name} · {e.role}</option>)}</select></Panel>{selected && <EmployeeView token={token} employeeId={selected} jury />}{<Panel title="2. Загрузить проверочные данные"><form className="upload-form" onSubmit={submitUpload}><label>employees JSON<input type="file" accept=".json,application/json" onChange={e => setUpload({ ...upload, employees: e.target.files?.[0] || null })} /></label><label>history CSV<input type="file" accept=".csv,text/csv" onChange={e => setUpload({ ...upload, history: e.target.files?.[0] || null })} /></label><button className="primary" type="submit">Импортировать датасет</button></form>{message && <div className="success">{message}</div>}{error && <div className="error">{error}</div>}</Panel>}</section>; }

function Panel({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="panel">{title && <h3>{title}</h3>}{children}</div>; }

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
